Soft Tech Exam/Skeletons/CSharp/SoftUniAirlines/SoftUniAirlines/Models/Flight.cs
namespace SoftUniAirlines.Models
{
    using System.ComponentModel.DataAnnotations;


    public class Flight
    {
        public int Id { get; set; }

        [Required]
        public string Departure  { get; set; }

        [Required]
        public string Destination { get; set; }

        [Required]
        public string Status { get; set; }
    }
}

Soft Tech Exam/Skeletons/CSharp/SoftUniAirlines/SoftUniAirlines/Controllers/FlightsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SoftUniAirlines.Data;
using SoftUniAirlines.Models;

namespace SoftUniAirlines.Controllers
{
    public class FlightsController : Controller
    {
        private readonly FlightDbContext context;

        public FlightsController(FlightDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        [Route("/")]
        public IActionResult Index()
        {
            List<Flight> flight =
                this.context.Flights
                .ToList();

            return View(flight);
        }

        [HttpGet]
        [Route("/create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("/create")]
        public IActionResult Create(Flight flight)
        {
            this.context.Flights.Add(flight);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("/edit/{id}")]
        public IActionResult Edit(int id)
        {
            Flight flight = this.context.Flights
                .Find(id);

            return View(flight);
        }

        [HttpPost]
        [Route("/edit/{id}")]
        public IActionResult Edit(Flight flight)
        {
            this.context.Flights.Update(flight);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("/delete/{id}")]
        public IActionResult Delete(int id)
        {
            Flight flight = this.context.Flights
                .Find(id);

            return View(flight);
        }

        [HttpPost]
        [Route("/delete/{id}")]
        public IActionResult Delete(Flight flight)
        {
            this.context.Flights.Remove(flight);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Soft Tech Exam/Skeletons/CSharp/SoftUniAirlines/SoftUniAirlines/Views/Flights/Create.cshtml
@model Flight

@{
    ViewBag.Title = "Create";
}

<div class="wrapper">
    @using (Html.BeginForm("Create", "Flights", FormMethod.Post, new { @class = "flight-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Add Flight
        </div>
        <div class="create-name">
            <div class="create-label">Departure</div>
            <input class="create-content" name="departure" />
        </div>
        <div class="create-name">
            <div class="create-label">Destination</div>
            <input class="create-content" name="destination" />
        </div>
        <div class="create-name">
            <div class="create-label">Status</div>
            @Html.DropDownList(nameof(Model.Status), new []
            {
                new SelectListItem{Text = "Delayed", Value = "Delayed"},
                new SelectListItem{Text = "Landed", Value = "Landed" },
                new SelectListItem{Text = "Expected", Value = "Expected"},
            }, new {@class = "create-submit"})
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Add</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Soft Tech Exam/Skeletons/CSharp/SoftUniAirlines/SoftUniAirlines/Views/Flights/Delete.cshtml
@model Flight

@{
    ViewData["Title"] = "Archive";
}

<div class="wrapper">
    @using (Html.BeginForm("Delete", "Flights", FormMethod.Post, new { @class = "flight-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Archive Flight
        </div>
        <div class="create-name">
            <div class="create-label">Departure</div>
            <input class="create-content" name="from" value="@Model.Departure" disabled="disabled" />
        </div>
        <div class="create-name">
            <div class="create-label">Destination</div>
            <input class="create-content" name="to" value="@Model.Destination" disabled="disabled" />
        </div>
        <div class="create-name">
            <div class="create-label">Status</div>
            <input class="create-content" name="status" disabled="disabled" value="@Model.Status" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Archive</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Soft Tech Exam/Skeletons/CSharp/SoftUniAirlines/SoftUniAirlines/Views/Flights/Edit.cshtml
@model Flight

@{
    ViewBag.Title = "Edit";
}

<div class="wrapper">
    @using (Html.BeginForm("Edit", "Flights", FormMethod.Post, new { @class = "flight-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Edit Flight
        </div>
        <div class="create-name">
            <div class="create-label">Departure</div>
            <input class="create-content" name="departure" value="@Model.Departure" />
        </div>
        <div class="create-name">
            <div class="create-label">Destination</div>
            <input class="create-content" name="destination" value="@Model.Destination" />
        </div>
        <div class="create-name">
            <div class="create-label">Status</div>
            @Html.DropDownList(nameof(Model.Status), new []
            {
                new SelectListItem{Text = "Delayed", Value = "Delayed", Selected = Model.Status =="Delayed"},
                new SelectListItem{Text = "Landed", Value = "Landed" , Selected = Model.Status == "Landed"},
                new SelectListItem{Text = "Expected", Value = "Expected", Selected = Model.Status == "Expected"},
            }, new {@class = "create-submit"})
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Edit</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Soft Tech Exam/Skeletons/CSharp/SoftUniAirlines/SoftUniAirlines/Views/Flights/Index.cshtml
@model IEnumerable<Flight>

@{
    ViewData["Title"] = "SoftUni Airlines";
}
<div class="wrapper">
    <div class="flight-create">
        <div class="create-header">
            SoftUni Airlines
        </div>
    </div>
    <br />
    <div class="button-holder">
        <a type="button" href="/create" class="log-button">Register Flight</a>
    </div>
    <div class="content">
        <div class="header">
            <div class="flight-label">Departure</div>
            <div class="flight-label">Destination</div>
            <div class="flight-label">Status</div>
            <div class="flight-label">Action</div>
        </div>
        <div class="main">
            @foreach (var flight in Model.ToList())
            {
                <div class="flight">
                    <div class="flight-name">
                        @(flight.Departure)
                    </div>
                    <div class="flight-name">
                        @(flight.Destination)
                    </div>
                    <div class="flight-name">
                        @(flight.Status)
                    </div>
                    <div class="flight-actions">
                        @Html.ActionLink("Edit", "Edit", "Flights", new { id = flight.Id }, new { @class = "edit-button" })
                        @Html.ActionLink("Archive", "Delete", "Flights", new { id = flight.Id }, new { @class = "delete-button" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Soft Tech Exam/Skeletons/CSharp/SoftUniAirlines/SoftUniAirlines/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>SoftUni Airlines</title>
    <link rel="stylesheet" href="~/css/reset.css" type="text/css" />
    <link rel="stylesheet" href="~/css/style.css" type="text/css" />
    <link rel="stylesheet" href="~/css/flight-style.css" type="text/css" />
</head>
<body>
    @RenderBody()
</body>
</html>